-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgpw2RGh5BtysUkYQ3
HhD9wlAUWMoZ2ijC3XR6GQhoK3qgCgYIKoZIzj0DAQehRANCAAQxoshrFLajVUSG
MOWdFUuBvWzdcJWJVISpcmsGJQKL6bVD3OgfReKO3O3R1+ShPWTxIYmyMYrZGzl2
ee3BEozz
-----END PRIVATE KEY-----